Remove qt as it is throwing the following error:
qt: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
Failed in installing qt

Update README for troubleshooting